modLoader="javafml" #mandatory
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]] #mandatory
modId="metallurgic" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Metallurgic" #mandatory
#updateJSONURL="" #optional
#displayURL="" #optional
#logoFile="metallurgic.png" #optional
credits="" #optional
authors="Bluperman949" #optional
description='''
placeholder description
'''
[[dependencies.metallurgic]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.metallurgic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
